language: cpp
compiler:
  - gcc
  - clang
env:
  - CONFIG=debug QT=qt5
  - CONFIG=release QT=qt5
before_script:
  - git submodule update --init --recursive
script:
  - qmake -r QMAKE_CXX=$CXX QMAKE_CC=$CC
  - unset CXX
  - unset CC
  - make
  - ./test/garnet_test
